baseURL = "https://dochugo.christopheducamp.com"
languageCode = "fr-fr"
DefaultContentLanguage = "fr-fr"

title = "Une documentation en français pour Hugo"

publishDir = "public"

theme = "docdock"
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/ChristopheDucamp/Doc-Hugo/edit/master/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
themeVariant = "blue" # choisir la variante du theme "green", "gold" , "gray", "blue" (blue par defaut)


[[menu.shortcuts]]
pre = "<h3>Plus</h3>"
name = "<i class='fa fa-github'></i> Repo Github"
identifier = "ds"
url = "https://github.com/ChristopheDucamp/Doc-Hugo"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Documentation Hugo "
identifier = "hugodoc"
url = "https://gohugo.io/documentation"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Crédits"
url = "/credits"
weight = 30
